---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: curity-idsvr-default-role-binding
  namespace: curity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: curity-idsvr-default-role
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: curity-idsvr-default-role
  namespace: curity
rules:
  - apiGroups: ["batch", "apps", ""]
    resources: ["pods", "services", "jobs"]
    verbs: ["get", "list", "watch"]