---
image:
  repository: image(schema)
  tag: tag(schema)
liquibase:
  changelog_file: changelog/mysql/quickstart_install.xml
services:
  mysqldb:
    name: mysqldb
    releaseNameOverride: curity
    waitfor: service